apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu
                operator: NotIn
                values:
                - "true"
      containers:
      - name: order-service
        image: us-west1-docker.pkg.dev/brave-smile-424210-m0/microservice/order-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "10m"
        volumeMounts:
          - name: tls-certificates
            mountPath: /certs
            readOnly: true
      volumes:
      - name: tls-certificates
        secret:
          secretName: order-service-tls-secret
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 5000  # App port
      targetPort: 5000
    - protocol: TCP
      port: 9100  # Prometheus metrics port
      targetPort: 9100

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: default
